export { Blog } from "./Blog";
export { Gallery } from "./Gallery";
export { WhoWeAre } from "./WhoWeAre";
export { Offer } from "./Offer";
export { Counter } from "./Counter";
export { Shop } from "./Shop";
export { About } from "./About";
export { OfferBanner } from "./OfferBanner";
export { Banner } from "./Banner";